name: cashier_store
description: "A new Flutter project."

publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  get: ^4.7.2
  get_storage: ^2.1.1
  http: ^1.4.0
  iconsax: ^0.0.8
  intl: ^0.20.2
  smooth_page_indicator: ^1.2.1

dev_dependencies:
  flutter_gen_runner: ^5.11.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter_gen:
  output: lib/core/assets/

flutter:
  uses-material-design: true

  assets:
    - assets/images/on_boarding_images/
    - assets/icons/
    - assets/fonts/
    - assets/logos/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins/Poppins-Black.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 800
